platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

#source 'https://github.com/CocoaPods/Specs.git' #为github的基础源仓库，必须添加

target 'HJBleDemo' do
    pod 'Masonry','~> 1.1.0'
    pod 'Toast','~> 4.0.0'
    pod 'SDWebImage', '~> 4.4'
    pod 'IQKeyboardManager','~> 6.5'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'WiseBaseKit', '~> 1.8.1'
#    pod 'MJRefresh', '~> 3.3.1'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'wiseBle', '~> 1.3.0'
    pod 'YYCache', '~> 1.0.4'
    pod 'MMPopupView', "~> 1.7.2"

end

target 'HJBleDemoTests' do
    pod 'wiseBle', '~> 1.3.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
