platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git' #为github的基础源仓库，必须添加

target 'HJBleDemo' do
    pod 'Masonry','~> 1.1.0'
    pod 'Toast','~> 4.0.0'
    pod 'SDWebImage', '~> 4.4'
    pod 'IQKeyboardManager','~> 6.5'
    pod 'pop', '~> 1.0.10'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'WiseBaseKit', '~> 1.7.9'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'wiseBle', '~> 1.2.2'
    pod 'YYCache', '~> 1.0.4'
    pod 'MMPopupView', "~> 1.7.2"
end
