plugins {
    id 'com.android.application'
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.hongjia.hjbledemo'
    compileSdk 31

//    buildToolsVersion "29.0.3"
    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }
    defaultConfig {
        applicationId "com.hongjia.hjbledemo"
        minSdk 21
        targetSdk 31
        versionCode 830
        versionName "8.3.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (keystorePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
            applicationVariants.all { variant ->
                variant.outputs.all { output ->
                    outputFileName = "HJBleDemo.apk"
                }
            }
        }
    }

    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }

    testOptions {
        unitTests.includeAndroidResources = true
        unitTests.all {
            systemProperty 'robolectric.dependency.repo.url', 'https://repo.maven.apache.org/maven2'
            if (project.hasProperty('robolectricJarDir')) {
                systemProperty 'robolectric.offline', 'true'
                systemProperty 'robolectric.dependency.dir', project.property('robolectricJarDir')
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'com.google.android.material:material:1.5.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.10.3'
    testImplementation 'org.mockito:mockito-inline:4.11.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation 'com.orhanobut:logger:2.2.0'
//    implementation 'com.blakequ.androidblemanager:bluetooth-manager-lib:2.1.5'
    implementation 'pub.devrel:easypermissions:3.0.0'
//    implementation 'com.githang:status-bar-compat:0.7'
    implementation ('com.github.niorgai:StatusBarCompat:2.3.3', {
        exclude group: 'androidx.appcompat:appcompat'
        exclude group: 'com.google.android.material:material'
    })
    implementation project(':fastble')
    implementation project(':wisekit')
}
